### ISSUE TITLE
Signature validation was skipped due to the registry not containing GPG keys for this provider

### ISSUE THREAD

**Issue by jamesgeddes** [NikolaLohinski/terraform-provider-jinja#17]
```sh
- Installed nikolalohinski/jinja v2.4.2. Signature validation was skipped due to the registry not containing GPG keys for this provider
```

Currently shows up in orange on the plan

**Comment by NikolaLohinski** [comment]
Hey @jamesgeddes 

I can't reproduce locally. I get:
```
23:02 $ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding nikolalohinski/jinja versions matching ">= 2.0.0"...
- Installing nikolalohinski/jinja v2.4.2...
- Installed nikolalohinski/jinja v2.4.2 (self-signed, key ID 92255C6F3FC37C6F)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
~/Documents/go/terraform-provider-jinja/exa

![Image](https://github.com/user-attachments/assets/ae042219-a10e-43aa-987f-2a85f94f577b)

mples on  main ✓ via 💠 default took 5s 
23:02 $ terraform plan
data.jinja_template.render: Reading...
data.jinja_template.render: Read complete after 0s [id=6526a8371218cc04818d71d325599daddeb9b8124bb07e5e32d5404fa3b936ec]

Changes to Outputs:
  + result = <<-EOT
        From context:
        foo: bar
        one:
        - two
        - 3
        
        From globals:
        - provider:
          - version: 2.4.2
          - commit: acfd6baa40a8ffe805ecf22d8ff25ecd26991c9c
          - date: 2024-11-23T16:11:16Z
          - repository: https://github.com/NikolaLohinski/terraform-provider-jinja
          - registry: registry.terraform.io/NikolaLohinski/jinja
        - gonja:
          - version: v2.3.2
        
        The following content is included from a different file:
        content
    EOT

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" no
```
when I run against the example.

I've also checked the registry and my GPG keys are still there and working just fine.

Could you give a little more context to how your running terraform ? Are you using a proxy or an internal registry perhaps ?

Thanks in advance

**Comment by jamesgeddes** [comment]
Sure, apologies for the omission.

My GitHub actions workflow is at

https://github.com/evoteum/estate-reusable-workflows/blob/main/.github/workflows/tofu-apply-all-environments.yml

**Comment by apparentlymart** [comment]
FWIW I think the main reason for the difference in @jamesgeddes's result vs @NikolaLohinski is that @jamesgeddes is using OpenTofu, while @NikolaLohinski is using HashiCorp Terraform.

These two products have different treatment of the shorthand form of a provider source address where no explicit hostname is specified:

* Terraform resolves `nikolalohinski/jinja` as `registry.terraform.io/nikolalohinski/jinja`
* OpenTofu resolves `nikolalohinski/jinja` as `registry.opentofu.org/nikolalohinski/jinja`

[The OpenTofu registry does have an entry for this provider](https://search.opentofu.org/provider/nikolalohinski/jinja/latest), but I guess it doesn't yet have a known public key for this provider, and so OpenTofu is treating it as unauthenticated.

It's ultimately @NikolaLohinski's decision whether to do this -- I mean no pressure to do it by this message -- but I think the way to make OpenTofu treat this provider as signed would be to [register the same public key with the OpenTofu registry](https://search.opentofu.org/docs/providers/adding#adding-the-gpg-key), and then the OpenTofu Registry will be able to return the same key information that the Terraform registry currently does.

---

As some background context in case you're not aware: OpenTofu cannot use the Terraform Registry, even if the hostname is explicitly specified, because [the Terraform Registry terms of use](https://registry.terraform.io/terms) disallow using any client other than Terraform CLI to access it:

> You may download providers, modules, policy libraries and/or other Services or Content from this website solely for use with, or in support of, HashiCorp Terraform.

**Comment by jamesgeddes** [comment]
@apparentlymart thanks for the explanation. I was not aware that Hashicorp did this. That makes me a sad panda.

@NikolaLohinski if you would like to support OpenTofu, I for one would be eternally grateful, though as @apparentlymart says, no obligation. Otherwise, please feel free to close the ticket.

**Comment by NikolaLohinski** [comment]
Thanks for the great explanation @apparentlymart 🙏 

I have not digged into the opentofu ecosystem yet so now is as good a time as any to do it.

I'll add my GPG key to that registry as well, as I definitely want to support it as well.

**Comment by NikolaLohinski** [comment]
Done in https://github.com/opentofu/registry/issues/1888; please confirm it works once the issue has been resolved and feel free to close this one 

cheers

**Comment by jamesgeddes** [comment]
@apparentlymart I see that the otf registry is still showing 451 on this provider. Now that the GPG keys are in place and  https://github.com/NikolaLohinski/terraform-provider-jinja/issues/18 is resolved, how do we give it a nudge?

**Comment by apparentlymart** [comment]
Hi @jamesgeddes,

I believe this "unavailable for legal reasons" message is unrelated to the key registration. There is no license declared in the repository content, and so to reduce the risk of copyright infringement the OpenTofu Registry shows only metadata about the provider and does not attempt to replicate the documentation from the repository. To make the documentation appear in the registry would require a release that contains a license file that contains the text of a known open source license. The list of licenses that the registry currently recognizes as suitable for documentation redistribution is in [`licences.json` in the Registry UI repository](https://github.com/opentofu/registry-ui/blob/main/licenses.json).

However, when I directly query the Provider Registry Protocol endpoint for the latest version of this provider I _do_ now see the registry reporting a public key with the id `92255C6F3FC37C6F`, which matches the one included in the `terraform init` output shared earlier, so I would expect `tofu init` to now report that this provider is self-signed in the same way that `terraform init` did, so I would hope that the original problem you reported has now been addressed. (Please check though! I only checked by querying the registry API directly, not by running `tofu init`.)

**Comment by jamesgeddes** [comment]
Just to check my understanding, does this mean that @NikolaLohinski needs to cut a new release that includes https://github.com/NikolaLohinski/terraform-provider-jinja/blob/main/LICENSE ?

**Comment by apparentlymart** [comment]
Indeed, I would expect that once the latest release includes that `LICENSE` file the registry UI should recognize that as being the MIT License, and so it should then be able to render the documentation associated with that release.

**Comment by jamesgeddes** [comment]
Thank you @apparentlymart 👍

**Comment by jamesgeddes** [comment]
I am now seeing 

```
- Installing nikolalohinski/jinja v2.4.2...
- Installed nikolalohinski/jinja v2.4.2 (signed, key ID 92255C6F3FC37C6F)
```
Looking good!

@NikolaLohinski you just need to cut a new release so that the documentation can be shown on https://search.opentofu.org/provider/nikolalohinski/jinja/latest

**Comment by NikolaLohinski** [comment]
Adding the LICENSE file to the release artifacts is also necessary it seems, which I've fixed in https://github.com/NikolaLohinski/terraform-provider-jinja/commit/d75efee84e7db8b397d13bebd8d63b102a17dd40

v2.4.3 should be fully working with opentofu now 🤞

**Comment by jamesgeddes** [comment]
Thanks @NikolaLohinski !

I am still seeing 451 on the registry, but perhaps it's a nightly job. Will check again tomorrow.

**Comment by NikolaLohinski** [comment]
Hmmm 2.4.3 doesn't show up in the registry

You guys know how often it is refreshed ?

**Comment by apparentlymart** [comment]
Hi @NikolaLohinski,

The registry does refresh periodically, but it's driven primarily by GitHub Actions and so sometimes it unfortunately gets a little "stuck", seemingly due to GitHub Actions worker contention, but we're still working with GitHub to figure out the complete answer.

Unfortunately it did get delayed for the last few days, but has run now. v2.4.3 of this provider is now available in the OpenTofu Registry. Thanks!

**Comment by jamesgeddes** [comment]
Looks all done to me @NikolaLohinski , feel free to close the ticket as complete 🥳
